# Generated by Django 5.2.5 on 2025-11-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='transition',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='background',
            name='transition_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
