# Generated by Django 5.2.5 on 2025-11-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(blank=True, default='processing', max_length=16, null=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('local_link', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('time_length', models.PositiveSmallIntegerField(blank=True, default=60, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('thumbnail', models.TextField(blank=True, default='', null=True)),
                ('author', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
