# Generated by Django 5.2.5 on 2025-08-29 05:27

import colorfield.fields
import common.models.picture
import datetime
import django.db.models.deletion
import django_resized.forms
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('full_size', models.BooleanField(default=True)),
                ('fit', models.CharField(blank=True, default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[512, None], upload_to=common.models.picture.picture)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='en', max_length=2, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_video', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoAnalisys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('language', models.CharField(blank=True, default='en', max_length=2, null=True)),
                ('transcriptions', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('viewed', models.BooleanField(blank=True, null=True)),
                ('liked', models.BooleanField(blank=True, null=True)),
                ('shared', models.BooleanField(blank=True, null=True)),
                ('created', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_from_video', to='video.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='video',
            name='analysis',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_videos_analysis', to='video.videoanalisys'),
        ),
    ]
