# Generated by Django 5.2.5 on 2025-08-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalisys',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
