# Generated by Django 5.2.5 on 2025-08-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videoanalisys_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='videoanalisys',
            old_name='url',
            new_name='link',
        ),
    ]
