# Generated by Django 5.2.5 on 2025-08-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_rename_url_video_link_rename_url_videoanalisys_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalisys',
            name='clean_transcriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
