# Generated by Django 5.2.5 on 2025-08-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_videoanalisys_clean_transcriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalisys',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
