# Generated by Django 5.2.5 on 2025-08-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_videoanalisys_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalisys',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoanalisys',
            name='requested_characteristics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoanalisys',
            name='status',
            field=models.CharField(blank=True, default='none', max_length=16, null=True),
        ),
    ]
