# Generated by Django 5.2.5 on 2025-08-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_videoanalisys_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='clean_transcriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
