# Generated by Django 5.2.5 on 2025-09-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_clean_transcriptions_video_transcriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='local_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(blank=True, default='none', max_length=16, null=True),
        ),
    ]
