# Generated by Django 5.2.5 on 2025-09-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_video_local_link_video_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='local_link',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
