# Generated by Django 5.2.5 on 2025-09-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_alter_video_local_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
