# Generated by Django 5.2.5 on 2025-09-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_video_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
