# Generated by Django 5.2.5 on 2025-09-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_video_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoanalisys',
            name='clean_transcriptions',
        ),
        migrations.RemoveField(
            model_name='videoanalisys',
            name='transcriptions',
        ),
        migrations.AddField(
            model_name='videoanalisys',
            name='ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='videoanalisys',
            name='started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='videoanalisys',
            name='worker_node',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
