# Generated by Django 5.2.5 on 2025-09-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_remove_videoanalisys_clean_transcriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='worker_node',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(blank=True, default='processing', max_length=16, null=True),
        ),
    ]
