# Generated by Django 5.2.5 on 2025-09-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_video_ended_video_started_video_worker_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalisys',
            name='status',
            field=models.CharField(blank=True, default='processing', max_length=16, null=True),
        ),
    ]
