# Generated by Django 5.2.5 on 2025-09-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_alter_videoanalisys_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='videoanalisys',
            name='language',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
