# Generated by Django 5.2.5 on 2025-09-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_alter_video_language_alter_videoanalisys_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
