# Generated by Django 5.2.5 on 2025-09-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0016_alter_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='requested_captions_language',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='requested_subtitles_language',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
