# Generated by Django 5.2.5 on 2025-09-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_video_requested_captions_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
