# Generated by Django 5.2.5 on 2025-09-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0018_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
