# Generated by Django 5.2.5 on 2025-09-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
