# Generated by Django 5.2.5 on 2025-09-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0021_alter_video_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
