# Generated by Django 5.2.5 on 2025-10-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0022_alter_video_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='local_link_sub',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
