# Generated by Django 5.2.5 on 2025-10-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0023_video_local_link_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='local_link_translated',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
