# Generated by Django 5.2.5 on 2025-10-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0024_video_local_link_translated'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='translated_clean_transcriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='translated_transcriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
