# Generated by Django 5.2.5 on 2025-10-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0025_video_translated_clean_transcriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='local_link_podcast',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='local_link_translated_audio',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
