# Generated by Django 5.2.5 on 2025-10-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0026_video_local_link_podcast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='podcast_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
