# Generated by Django 5.2.5 on 2025-10-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0027_video_podcast_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='local_link_podcast_video',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='podcast_language',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='podcast_srt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
