# Generated by Django 5.2.5 on 2025-10-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0028_video_local_link_podcast_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='local_link_podcast_srt',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
