# Generated by Django 5.2.5 on 2025-10-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0029_video_local_link_podcast_srt'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='local_link_original_srt',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='local_link_podcast_diarization',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='podcast_diarization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='podcast_instrucctions',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='podcast_length',
            field=models.CharField(blank=True, default='medium', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='podcast_mood',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='podcast_name',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
