# Generated by Django 5.2.5 on 2025-08-29 04:58

import colorfield.fields
import common.models.country
import common.models.picture
import common.models.system
import common.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItemGalleryPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('full_size', models.BooleanField(default=True)),
                ('fit', models.CharField(blank=True, default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, scale=None, size=[3840, None], upload_to=common.models.picture.picture)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('task_name', models.CharField(max_length=256)),
                ('task_type', models.CharField(blank=True, choices=[('back-end', 'back-end'), ('front-end', 'front-end'), ('server', 'server'), ('ci-cd', 'ci-cd'), ('design', 'design'), ('documentation', 'documentation'), ('change', 'change'), ('improvement', 'improvement'), ('bugfix', 'bugfix'), ('integration', 'integration'), ('testing', 'testing')], default='front-end', max_length=32, null=True)),
                ('hours', models.PositiveSmallIntegerField(default=1, verbose_name='Development time (hours)')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=255, unique=True, validators=[common.validators.ModelValidators.name])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=255, unique=True, validators=[common.validators.ModelValidators.name])),
                ('code', models.CharField(max_length=2, unique=True)),
                ('phone_code', models.CharField(max_length=2, unique=True)),
                ('img_flag', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, scale=None, size=[128, 128], upload_to=common.models.country.picture)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.URLField(blank=True, max_length=255, null=True)),
                ('full_size', models.BooleanField(default=True)),
                ('fit', models.CharField(blank=True, default='cover', max_length=16, null=True)),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#fff', image_field=None, max_length=25, null=True, samples=None)),
                ('img_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, scale=None, size=[3840, None], upload_to=common.models.picture.picture)),
                ('position', models.CharField(blank=True, choices=[('center', 'center'), ('top', 'top'), ('right', 'right'), ('bottom', 'bottom'), ('left', 'left'), ('bottom_right', 'bottom_right'), ('bottom_left', 'bottom_left')], default='center', max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=256, verbose_name='Sprint Name')),
                ('price_per_hour', models.PositiveSmallIntegerField(default=300)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=32, unique=True, validators=[common.validators.ModelValidators.name])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('site_name', models.CharField(default='My API', max_length=32)),
                ('img_logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=95, scale=None, size=[512, 512], upload_to=common.models.system.picture)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('user_data', models.TextField(blank=True, null=True)),
                ('llm_positivity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('llm_negativity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('llm_happiness', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('llm_warning', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('llm_mistery', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
